### ISSUE TITLE
Some way to activate doc search by clicking/tapping

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr-docs#116]
As of the 0.16 docs, the only way to search the docs is to just start typing. Any keystroke is interpreted as an attempt to initiate a search. While this is very interesting, it has two problems:

* It is not very discoverable. I assumed doc search had been removed until I activated it by accident
* There is no way to activate it on mobile— at all

Expected behavior: There should be a magnifying glass button or "search" link somewhere that kicks open the search prompt.

**Comment by bjornbytes** [comment]
I added an adorable magnifying glass to the website

**Comment by mcclure** [comment]
🔎
