### ISSUE TITLE
Title anchors don't work in Safari

### ISSUE THREAD

**Issue by KelseyHigham** [bjornbytes/lovr-docs#138]
like this -> https://lovr.org/docs/master/Pass#tally

**Comment by KelseyHigham** [comment]
(they do work in Chrome and Firefox)

**Comment by bjornbytes** [comment]
Also why aren't they links on there?  Fancy header links appear to be guides-only

**Comment by bjornbytes** [comment]
[This](https://github.com/bjornbytes/lovr.org/blob/7eb85f451bd548b3410f947a62781d81e5c6f7db/.lua/generate.lua#L223-L228) part of the docs generator could be extracted into a function that runs on more pages.

The anchor IDs on other pages are actually being added [dynamically](https://github.com/bjornbytes/lovr.org/blob/7eb85f451bd548b3410f947a62781d81e5c6f7db/js/docs.js#L131-L134) by JS right now, which won't work if someone disables JS (I've been trying to get better about that).

**Comment by KelseyHigham** [comment]
oh, maybe Safari hops to an anchor before JS runs

**Comment by bjornbytes** [comment]
This is fixed now!
