### ISSUE TITLE
missing top level `summary` in various files

### ISSUE THREAD

**Issue by pterror** [bjornbytes/lovr-docs#148]
full list as of 0.17.0 docs:
```
data/TextureFormat
graphics/DataLayout
graphics/DataType
graphics/TextureType
graphics/TextureUsage
headset/DeviceAxis
headset/DeviceButton
headset/Device
```

**Comment by bjornbytes** [comment]
Added these missing summaries, and updated the docs generator to warn if any enums are missing summaries/descriptions so it won't happen again.  Thanks!
