### ISSUE TITLE
ShaderBlock documentation issues

### ISSUE THREAD

**Issue by porglezomp** [bjornbytes/lovr-docs#17]
The `ShaderBlock:send` notes mention passing tables of numbers, but the method signatures only suggest allowing `Blob`s:

> For scalar or vector types, use tables of numbers or `vec3s` for each vector.

The signature of `lovr.graphics.newShaderBlock` doesn't describe the first argument, and it isn't demonstrated on that page, but it is shown on the `ShaderBlock` main page example.

**Comment by bjornbytes** [comment]
Fixed these two issues and added the missing `readable` flag.
