### ISSUE TITLE
add HTTPS for lovr.org

### ISSUE THREAD

**Issue by cvan** [bjornbytes/lovr-docs#2]
it'd be nice if http://lovr.org/ was served at https://lovr.org/

here are some instructions of using CloudFlare as a free CDN + HTTPS provider: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by bjornbytes** [comment]
https://lovr.org ❤️

**Comment by cvan** [comment]
that was quick - thanks!
