### ISSUE TITLE
Add arguments and output values for newVec3, vec3, etc

### ISSUE THREAD

**Issue by darltrash** [bjornbytes/lovr-docs#55]
Instead of adding a description like "`This function takes the same arguments as Vec3:set.`", Please add argument and output values for the constructors.
This is very useful for auto-bindings. For example: [Löwr](https://github.com/darltrash/lowr)

**Comment by bjornbytes** [comment]
Would you like to submit a pull request for this improvement?

**Comment by darltrash** [comment]
> Would you like to submit a pull request for this improvement?

I'll try my best!

**Comment by darltrash** [comment]
> Would you like to submit a pull request for this improvement?
https://github.com/bjornbytes/lovr-docs/pull/56

**Comment by bjornbytes** [comment]
This is done
