### ISSUE TITLE
A few typos, clarity tweaks, and omissions

### ISSUE THREAD

**Issue by KelseyHigham** [bjornbytes/lovr-docs#80]
## small changes

- [x] “torwards”
https://lovr.org/docs/v0.15.0/Mat4:target

- [x] “affect” should be “effect”
https://lovr.org/docs/Collider:applyTorque

- [x] :detectOverlaps should read :computeOverlaps
https://lovr.org/docs/World:overlaps

- [x] This page should list https://lovr.org/docs/World:newMeshCollider
https://lovr.org/docs/Collider

- [x] This setDimensions() function doesn’t actually exist; it should read setRadius()
https://lovr.org/docs/SphereShape

- [x] The equation at the bottom has a typo
https://lovr.org/docs/Vec4:length

- [x] Paragraph 1, last sentence, should specify that it's the center of the *floor*
https://lovr.org/docs/lovr.headset

- [x] Return value is wrong:
https://lovr.org/docs/v0.15.0/lovr.math.newMat4
https://lovr.org/docs/v0.15.0/lovr.math.mat4

- [x] For people who follow tutorials by typing every example, the second code block should link to a monkey model:
https://lovr.org/docs/v0.15.0/Callbacks_and_Modules

- [x] This page has a broken link to this image:
https://lovr.org/docs/v0.15.0/Simple_Lighting
https://barelyconsciousgames.blogspot.com/2020/07/simple-lighting-for-lovr-phong-model-in.html

## bigger changes

- [x] These pages should clarify that :collide creates contact joints, and :update processes those joints
https://lovr.org/docs/World:collide
https://lovr.org/docs/World:update
https://lovr.org/docs/v0.15.0/World

- [x] It would be cool if this page said how it computes overlaps. Some questions I had while reading it:
https://lovr.org/docs/World:computeOverlaps
• Does it check collision between AABBs? If that's all I want, can I use it for that?
• Does it use a fast algorithm, or should I avoid calling it many times per frame?
• I think at some point, someone said that ODE uses spatial hashing – is this that?

- [x] "Returns the original matrix" is misleading. This seems to be the default text on most vector pages. Might make sense to default to "returns the new matrix" or "returns the changed matrix" or something
https://lovr.org/docs/Mat4:lookAt

**Comment by jmiskovic** [comment]
A good list. I started fixing the easy ones in a PR.

**Comment by bjornbytes** [comment]
Finished the rest of these
