### ISSUE TITLE
In Safari on macOS, most Example embeds crash the tab or freeze the OS

### ISSUE THREAD

**Issue by KelseyHigham** [bjornbytes/lovr-docs#82]
Since this impacts the ability to use Safari to read documentation, I think it makes sense not to embed Examples in Safari. Or at least hide them behind a play button.

Tested in macOS Monterey 12.2.1, on [this Intel Mac](https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.8-15-dual-graphics-mid-2015-retina-display-specs.html).

---

### These don’t crash:

Intro
- Hello World
- Spinning Cube
- 3D Model
- 360 Photo
- Tracked Hands

Interaction
- Controller Models (doesn’t render, but doesn’t crash)
- Hand Tracking (doesn’t render, but doesn’t crash)

Locomotion
- Environment
- Grid
- Skybox

Lighting

Animation

Physics
- Boxes
- Hand Physics
- Saloon Door

Audio
- Playback (doesn’t play, but doesn’t crash)
- Spatialization
- Sine Wave Generator (doesn’t play, but doesn’t crash)

Effects
- Stereo Image
- Cubemap Texturing

UI

Optimization
- Instancing (freezes for a few minutes, and just renders black eventually, but doesn’t crash)
- Mask (doesn’t render, but doesn’t crash)

Debugging

---

### These crash:

Intro
- Shapes
- Thread
- Custom Mesh

Interaction
- Pointer
- Pointer UI
- Physics Pointer
- Dragging

Locomotion
- Basic Thumbsticks
- Teleportation Flat
- Teleportation Colliders
- Walking In Place

Environment
- Terrain - Heightmap (technically this eats my GPU and freezes my computer, but doesn’t crash)
- Terrain - Procedural (technically this eats my GPU and freezes my computer, but doesn’t crash)

Lighting
- PBR Materials
- Animation
- Playback
- 2 Bone IK

Physics
- Drawing Colliders
- Newtons Cradle
- Wrecking Ball
- Zip Line

Audio
- Directivity
- Mute (doesn’t play; crashes after a few seconds)

Effects
- Blur

UI
- Spectator Camera
- Window HUD

Optimization

Debugging
- FPS Controls (displays an error for a second, then crashes)
- Raw Input (crashes after a few seconds)

**Comment by bjornbytes** [comment]
Definitely :+1: to disabling autoplay and/or making it opt-in

**Comment by bjornbytes** [comment]
This is technically resolved by deleting the embeds :confused-yay:

Moving to WebGPU will also probably work much better in Safari.
