### ISSUE TITLE
Example linked in Simple_Lighting is incompatible with latest lovr

### ISSUE THREAD

**Issue by eigenbom** [bjornbytes/lovr-docs#94]
Link in https://lovr.org/docs/Simple_Lighting to https://barelyconsciousgames.com/lovr-phong.zip is incompatible with latest lovr.

**Comment by bjornbytes** [comment]
[Yeah](https://github.com/bjornbytes/lovr/issues/601#issuecomment-1317974621), I think since I can't update it the link ought to be removed.

**Comment by bjornbytes** [comment]
Hm, or I could upload a new version and swap the link

**Comment by bjornbytes** [comment]
Ok, updated
