### ISSUE TITLE
Function parameters not clear in docs

### ISSUE THREAD

**Issue by eigenbom** [bjornbytes/lovr-docs#99]
I think the documentation for functions that have different variations isn't clear. Take [Pass:plane](https://lovr.org/docs/Pass:plane) as an example. The API documentation states that the transform parameter is a Mat4, or alternatively "can be provided as a position, 2-component scale, and rotation using a combination of Vectors, and numbers.". Would be nice to see each variant form explicitly documented, e.g.,  `Pass:plane( pos_x, pos_y, pos_z, scale_x, scale_y, quat_x, quat_y, quat_z, quat_w, ... )` (if indeed that's an accepted form, i'm not sure...)

**Comment by bjornbytes** [comment]
There's some previous discussion [here](https://github.com/bjornbytes/lovr-docs/issues/38).

An issue with documenting all variants is the combinatorial explosion of all the ways to provide a matrix (13+ for some functions).  I think it could be manageable if all the variants were displayed in a condensed table and you could click to expand/switch between them, but on the current website it would be a long, unreadable mess to scroll through.

**Comment by eigenbom** [comment]
Ah cool, closing this in favour of the other discussion.
